language: java
jdk:
  - oraclejdk8 
before_install:
 - chmod +x gradlew
script:
  - ./gradlew check
before_install:
  - wget $GOOGLE_APPLICATION_CREDENTIALS_FILE
after_success:
  - bash <(curl -s https://codecov.io/bash)
