language: java
jdk:
  - oraclejdk8 
before_install:
 - chmod +x gradlew
script:
  - ./gradlew check
before_install:
  - wget https://storage.googleapis.com/apppokerserver.appspot.com/$GOOGLE_APPLICATION_CREDENTIALS
after_success:
  - bash <(curl -s https://codecov.io/bash)
